import { NextResponse } from "next/server";
import { validateApiKey, logApiRequest } from "@/lib/api-utils";
import { db } from "@/lib/db";
import { endUsers, profiles, timelineEvents, memories } from "@/lib/db/schema";
import { eq, and, desc } from "drizzle-orm";
import { z } from "zod";

const GetContextSchema = z.object({
  userId: z.string().min(1),
  limitTimeline: z.number().max(20).optional().default(5),
});

export async function POST(request: Request) {
  const startTime = Date.now();
  let projectId = "unknown";
  let requestPayload: any = {};

  try {
    const auth = await validateApiKey(request);
    if (auth.error) {
      return NextResponse.json({ error: auth.error }, { status: auth.status });
    }
    projectId = auth.projectId!;

    requestPayload = await request.json();
    const parsed = GetContextSchema.safeParse(requestPayload);
    if (!parsed.success) {
      return NextResponse.json({ error: "Invalid payload", details: parsed.error.issues }, { status: 400 });
    }

    const { userId, limitTimeline } = parsed.data;

    // Resolve endUser
    const userRecord = await db.query.endUsers.findFirst({
      where: and(eq(endUsers.projectId, projectId), eq(endUsers.externalId, userId)),
    });

    if (!userRecord) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    // 1. Fetch Profile
    const profile = await db.query.profiles.findFirst({
      where: eq(profiles.endUserId, userRecord.id),
    });

    // 2. Fetch Recent Timeline Events
    const recentEvents = await db.query.timelineEvents.findMany({
      where: eq(timelineEvents.endUserId, userRecord.id),
      orderBy: [desc(timelineEvents.date)],
      limit: limitTimeline,
    });

    // 3. (Optional) Compile it into a single LLM-ready summary string
    // In the future, this string would be generated by a lightweight LLM call or a prompt template
    let summary = `This user `;
    if (profile?.identity && Object.keys(profile.identity).length > 0) {
      summary += `identifies as ${JSON.stringify(profile.identity)}. `;
    } else {
      summary += `is a user of the system. `;
    }
    
    if (profile?.projects && (profile.projects as string[]).length > 0) {
      summary += `They are currently working on ${(profile.projects as string[]).join(", ")}. `;
    }

    const response = {
      summary: summary.trim(),
      identity: profile?.identity || {},
      skills: profile?.skills || [],
      projects: profile?.projects || [],
      goals: profile?.goals || [],
      preferences: profile?.preferences || [],
      recent_activity: recentEvents.map(e => ({ date: e.date.toISOString().split('T')[0], description: e.description })),
      confidence: profile?.confidenceScore || 0,
    };

    logApiRequest({ projectId, method: "POST", endpoint: "/api/v1/get-context", requestPayload, responsePayload: response, statusCode: 200, durationMs: Date.now() - startTime });
    return NextResponse.json(response);

  } catch (error: any) {
    logApiRequest({ projectId, method: "POST", endpoint: "/api/v1/get-context", requestPayload, responsePayload: null, statusCode: 500, durationMs: Date.now() - startTime, errorMessage: error.message });
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
